# Generated by Django 4.1.2 on 2022-10-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
    ]
