# Generated by Django 4.1.2 on 2022-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
