# Generated by Django 4.1.2 on 2022-10-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programme', '0004_specialization_studies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studies', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=150)),
                ('credits', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('specialization', models.ManyToManyField(null=True, to='training_programme.specialization')),
            ],
        ),
    ]
