# Generated by Django 4.1.2 on 2022-10-11 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('training_programme', '0005_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
