# Generated by Django 4.1.2 on 2022-10-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programme', '0007_subjects_school_year_subjects_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('term', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='school_year',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='term',
        ),
    ]
