# Generated by Django 4.1.2 on 2022-10-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programme', '0008_schoolyear_remove_subjects_school_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='term',
            field=models.CharField(blank=True, choices=[('I', 'Học kì I'), ('II', 'Học kì II')], max_length=10, null=True),
        ),
    ]
