# Generated by Django 4.1.2 on 2022-10-12 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training_programme', '0009_alter_schoolyear_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='school_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training_programme.schoolyear'),
        ),
    ]
