# Generated by Django 4.1.2 on 2022-10-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_programme', '0010_subjects_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='term',
            field=models.CharField(blank=True, choices=[('I', 'Học kì I'), ('II', 'Học kì II'), ('III', 'Học kì III'), ('IV', 'Học kì IV'), ('KP', 'Học kì phụ')], max_length=10, null=True),
        ),
    ]
