# Generated by Django 4.1.2 on 2022-10-11 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('training_programme', '0006_subjects_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('studis', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('base_point', models.FloatField(blank=True, null=True)),
                ('foreign_language', models.CharField(choices=[('PASS', 'Đạt'), ('NOT PASS', 'Chưa đạt')], max_length=10)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_programme.department')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_programme.specialization')),
                ('specializationClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_programme.specializationclass')),
            ],
        ),
    ]
